In [68]:
# BackPropogation Algorithm

import numpy as np
x = np.array(([2,9],[1,5],[3,6]),dtype=float)
y = np.array(([92],[86],[89]),dtype=float)
x = x/np.amax(x,axis=0)
y = y/100

def sigmoid(x):
    return 1/(1+np.exp(-x))

def derivative(x):
    return x*(1-x)

epoch = 5000
lr = 0.1
input = 2
hidden = 3
output = 1

wh = np.random.uniform(size=(input,hidden))
bh = np.random.uniform(size=(1,hidden))
wout = np.random.uniform(size=(hidden,output))
bout = np.random.uniform(size=(1,output))

for i in range(epoch):
    # Forward Propogation
    act = sigmoid(np.dot(x,wh)+bh)
    output = sigmoid(np.dot(act,wout)+bout)

    # Next part not needed i.e. doesnt affect output
    doutput = (y-output)*derivative(output) #Backpropagation
    dhidden = doutput.dot(wout.T)*derivative(act) #HiddenLayer contribution to error 

# (Isn't needed for output) Dotproduct of nextlayererror & currentlayerop
wout += act.T.dot(doutput) *lr
wh += x.T.dot(dhidden) *lr

print("Input: \n" + str(x)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.77635948]
 [0.76802496]
 [0.78129511]]

[[0.02493965]
 [0.01638651]
 [0.01857474]] [[2.55152779e-05 3.17805912e-03 1.56063264e-04]
 [2.03215401e-05 2.42806035e-03 1.26899693e-04]
 [1.57302157e-05 2.05534468e-03 1.29407285e-04]]
